### ISSUE TITLE
Pointer Issue

### ISSUE THREAD

**Issue by maxwell92** [lth2015/yce#16]
We can see in the [code](https://github.com/lth2015/yce/blob/master/src/app/backend/controller/yce/login/login.go):

line 19: "func (lc *LoginController) check(name, password string) (*myuser.User, *myerror.YceError) {"
line 42: "func (lc *LoginController) session(user *myuser.User) *myerror.YceError {
lc is a *pointer* (actually it's called *pointer receiver*) 

But in
line 72: "func (lc LoginController) Post() {"
lc is just a normal variable.

What's the difference between the two lc? or it's just a typo?

**Comment by lth2015** [comment]
手误
